<?php declare(strict_types=1);

/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Hyva\Admin\ViewModel\HyvaGrid\CellInterface $cell */

/** @var \Magento\Sales\Model\Order\Address $address */
$address = $cell->getRow()->getCell('billing_address')->getRawValue();

?>

<?= $escaper->escapeHtml($address ? $address->getName() : '') ?>
