<?php declare(strict_types=1);

/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Hyva\Admin\ViewModel\HyvaGrid\CellInterface $cell */
$cell = $block->getData('cell');
$key = $cell->getColumnDefinition()->getKey();
$labelCell = $cell->getRow()->getCell($key . '_label');
?>

<img src="<?= $escaper->escapeHtmlAttr($cell->getTextValue()) ?>"
     alt="<?= $labelCell ? $escaper->escapeHtmlAttr($labelCell->getTextValue()) : '' ?>"/>
