<?php declare(strict_types=1);

/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Hyva\Admin\ViewModel\HyvaGrid\CellInterface $cell */
$cell = $block->getData('cell');

// Example template combining values from two cells in a row.

$key        = $cell->getColumnDefinition()->getKey();
$labelColum = $key . '_label';
$labelCell  = $cell->getRow()->getCell($labelColum);
$label      = $labelCell ? $labelCell->getTextValue() : '';

?>
<div>
    <img src="<?= $escaper->escapeHtmlAttr($cell->getTextValue()) ?>" alt="<?= $escaper->escapeHtmlAttr($label) ?>"/>
</div>
